### ISSUE TITLE
allow port specification

### ISSUE THREAD

**Issue by defunctzombie** [juliangruber/tapedeck#6]
It is really annoying when the port changes between various restarts. Since the tool is for manual users (versus some auto config system) would be nice to have a way to specify the port on the cli.

Maybe consider this setup (I do this with zuul).

Default cli usage always runs in phantom js:
`tapedeck test/*.js` This is great for putting into `npm test`

Local testing with --server flag
`tapedeck --server 9000 test/*.js` and now I have a server for locally testing

**Comment by juliangruber** [comment]
I want that too, there is no real benefit with random ports. Will do!

**Comment by juliangruber** [comment]
Also, the core should be a library and the cli part just a bin script
